SELECT
    TABLE_NAME,
    COLUMN_NAME,
    CONSTRAINT_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
    -> FROM
    information_schema.KEY_COLUMN_USAGE
    -> WHERE
    TABLE_SCHEMA = "zeeguu_test" AND CONSTRAINT_NAME <> 'PRIMARY'
    AND REFERENCED_TABLE_NAME IS NOT NULL;
