JSON_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
SIMPLE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"
SIMPLE_DATE_FORMAT = "%Y-%m-%d"

# Event names for the UserActivityData table
UMR_OPEN_ARTICLE_ACTION = "OPEN ARTICLE"
UMR_ARTICLE_FOCUSED_ACTION = "ARTICLE FOCUSED"
UMR_ARTICLE_CLOSED_ACTION = "ARTICLE CLOSED"

UMR_TRANSLATE_TEXT_ACTION = "TRANSLATE TEXT"
UMR_SPEAK_TEXT_ACTION = "SPEAK TEXT"
UMR_SEND_SUGGESTION_ACTION = "SEND SUGGESTION"
UMR_STAR_ARTICLE_ACTION = "STAR ARTICLE"
UMR_LIKE_ARTICLE_ACTION = "LIKE ARTICLE"

UMR_ARTICLE_LOST_FOCUS_ACTION = "ARTICLE LOST FOCUS"
UMR_USER_FEEDBACK_ACTION = "USER FEEDBACK"


# these are not saved since 2021-04. why?
UMR_OPEN_ALTERMENU_ACTION = "OPEN ALTERMENU"
UMR_CLOSE_ALTERMENU_ACTION = "CLOSE ALTERMENU"
UMR_UNDO_TEXT_TRANSLATION_ACTION = "UNDO TEXT TRANSLATION"
UMR_CHANGE_ORIENTATION_ACTION = "CHANGE ORIENTATION"
UMR_UNFOLLOW_FEED = "UNFOLLOW FEED"
UMR_ARTICLES_REQUESTED_FROM_ZEEGUU = "ARTICLES REQUESTED FROM ZEEGUU"
UMR_USER_SCROLL_ACTION = "SCROLL"

# not used since een longer
UMR_OPEN_STARRED_ARTICLE_ACTION = "OPEN STARRED ARTICLE"

# never used?
UMR_WORDS_REVIEW = "WORDS REVIEW"


# Event types for word_knowledge/WordInteractionHistory
WIH_READ_CLICKED = 0
WIH_READ_NOT_CLICKED_IN_SENTENCE = 1
WIH_READ_NOT_CLICKED_OUT_SENTENCE = 2
WIH_CORRECT_EX_RECOGNIZE = 3
WIH_CORRECT_EX_TRANSLATE = 4
WIH_CORRECT_EX_CHOICE = 5
WIH_CORRECT_EX_MATCH = 6
WIH_WRONG_EX_RECOGNIZE = 7
WIH_WRONG_EX_TRANSLATE = 8
WIH_WRONG_EX_CHOICE = 9
WIH_WRONG_EX_MATCH = 10

# time delta in which consecutive bookmarks are merged together
TIMEDELTA = 120
