JSON_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
SIMPLE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"
SIMPLE_DATE_FORMAT = "%Y-%m-%d"

# Event names for the UserActivityData table
EVENT_OPEN_ARTICLE = "OPEN ARTICLE"
EVENT_ARTICLE_FOCUSED = "ARTICLE FOCUSED"
EVENT_ARTICLE_CLOSED = "ARTICLE CLOSED"

EVENT_TRANSLATE_TEXT = "TRANSLATE TEXT"
EVENT_SPEAK_TEXT = "SPEAK TEXT"
EVENT_SEND_SUGGESTION = "SEND SUGGESTION"
EVENT_STAR_ARTICLE = "STAR ARTICLE"
EVENT_LIKE_ARTICLE = "LIKE ARTICLE"

EVENT_ARTICLE_LOST_FOCUS = "ARTICLE LOST FOCUS"
EVENT_USER_FEEDBACK = "USER FEEDBACK"
EVENT_USER_SCROLL = "SCROLL"


# these are not saved since 2021-04. why?
EVENT_OPEN_ALTERMENU = "OPEN ALTERMENU"
EVENT_CLOSE_ALTERMENU = "CLOSE ALTERMENU"
EVENT_UNDO_TEXT_TRANSLATION = "UNDO TEXT TRANSLATION"
EVENT_CHANGE_ORIENTATION = "CHANGE ORIENTATION"
EVENT_UNFOLLOW_FEED = "UNFOLLOW FEED"
EVENT_ARTICLES_REQUESTED_FROM_ZEEGUU = "ARTICLES REQUESTED FROM ZEEGUU"

# not used since een longer
STARRED_ARTICLE_ACTION = "OPEN STARRED ARTICLE"

# never used?
WORDS_REVIEW = "WORDS REVIEW"


OPENING_ACTIONS = [
    EVENT_OPEN_ARTICLE,
    STARRED_ARTICLE_ACTION,
    EVENT_ARTICLE_FOCUSED,
]

LEGACY_OPENING = ["UMR - " + e for e in OPENING_ACTIONS]


INTERACTION_ACTIONS = [
    EVENT_TRANSLATE_TEXT,
    EVENT_SPEAK_TEXT,
    EVENT_OPEN_ALTERMENU,
    EVENT_CLOSE_ALTERMENU,
    EVENT_UNDO_TEXT_TRANSLATION,
    EVENT_SEND_SUGGESTION,
    EVENT_CHANGE_ORIENTATION,
    EVENT_USER_SCROLL,
    EVENT_STAR_ARTICLE,
    EVENT_LIKE_ARTICLE,
    EVENT_USER_FEEDBACK,
]

LEGACY_INTERACTION = ["UMR - " + e for e in INTERACTION_ACTIONS]


CLOSING_ACTIONS = [EVENT_ARTICLE_CLOSED, EVENT_ARTICLES_REQUESTED_FROM_ZEEGUU]

LEGACY_CLOSING = ["UMR - " + e for e in CLOSING_ACTIONS]

ALL_ARTICLE_INTERACTION_ACTIONS = (
    OPENING_ACTIONS + INTERACTION_ACTIONS + [EVENT_ARTICLE_CLOSED]
)

# Parameter that controls after how much time (in minutes) the session is expired
READING_SESSION_TIMEOUT = 2


# Event types for word_knowledge/WordInteractionHistory
WIH_READ_CLICKED = 0
WIH_READ_NOT_CLICKED_IN_SENTENCE = 1
WIH_READ_NOT_CLICKED_OUT_SENTENCE = 2
WIH_CORRECT_EX_RECOGNIZE = 3
WIH_CORRECT_EX_TRANSLATE = 4
WIH_CORRECT_EX_CHOICE = 5
WIH_CORRECT_EX_MATCH = 6
WIH_WRONG_EX_RECOGNIZE = 7
WIH_WRONG_EX_TRANSLATE = 8
WIH_WRONG_EX_CHOICE = 9
WIH_WRONG_EX_MATCH = 10

# time delta in which consecutive bookmarks are merged together
TIMEDELTA = 120
