JSON_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
SIMPLE_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S%z"
SIMPLE_DATE_FORMAT = "%Y-%m-%d"

# Event names for the UserActivityData table
UMR_OPEN_ARTICLE_ACTION = "UMR - OPEN ARTICLE"
UMR_OPEN_STARRED_ARTICLE_ACTION = "UMR - OPEN STARRED ARTICLE"
UMR_ARTICLE_FOCUSED_ACTION = "UMR - ARTICLE FOCUSED"
UMR_ARTICLE_CLOSED_ACTION = "UMR - ARTICLE CLOSED"

UMR_TRANSLATE_TEXT_ACTION = "UMR - TRANSLATE TEXT"
UMR_SPEAK_TEXT_ACTION = "UMR - SPEAK TEXT"
UMR_OPEN_ALTERMENU_ACTION = "UMR - OPEN ALTERMENU"
UMR_CLOSE_ALTERMENU_ACTION = "UMR - CLOSE ALTERMENU"
UMR_UNDO_TEXT_TRANSLATION_ACTION = "UMR - UNDO TEXT TRANSLATION"
UMR_SEND_SUGGESTION_ACTION = "UMR - SEND SUGGESTION"
UMR_CHANGE_ORIENTATION_ACTION = "UMR - CHANGE ORIENTATION"
UMR_STAR_ARTICLE_ACTION = "UMR - STAR ARTICLE"
UMR_LIKE_ARTICLE_ACTION = "UMR - LIKE ARTICLE"

UMR_ARTICLE_LOST_FOCUS_ACTION = "UMR - ARTICLE LOST FOCUS"
UMR_USER_FEEDBACK_ACTION = "UMR - USER FEEDBACK"
UMR_WORDS_REVIEW = "UMR - WORDS REVIEW"

UMR_UNFOLLOW_FEED = "UMR - UNFOLLOW FEED"

# Event types for word_knowledge/WordInteractionHistory
WIH_READ_CLICKED = 0
WIH_READ_NOT_CLICKED_IN_SENTENCE = 1
WIH_READ_NOT_CLICKED_OUT_SENTENCE = 2
WIH_CORRECT_EX_RECOGNIZE = 3
WIH_CORRECT_EX_TRANSLATE = 4
WIH_CORRECT_EX_CHOICE = 5
WIH_CORRECT_EX_MATCH = 6
WIH_WRONG_EX_RECOGNIZE = 7
WIH_WRONG_EX_TRANSLATE = 8
WIH_WRONG_EX_CHOICE = 9
WIH_WRONG_EX_MATCH = 10

# time delta in which consecutive bookmarks are merged together
TIMEDELTA = 120

UMR_ARTICLES_REQUESTED_FROM_ZEEGUU = "UMR - ARTICLES REQUESTED FROM ZEEGUU"
UMR_USER_SCROLL_ACTION = "UMR - SCROLL"
