import zeeguu.core
from zeeguu.core.model import Article, Language
from nltk.tokenize import sent_tokenize

JUNK_PATTERNS_TO_REMOVE = [
    "\nAdvertisement\n",
    "\ntrue\n",
    "Automatisk oplæsning\n",
    "Som registreret bruger kan du overvåge emner og journalister og modtage nyhederne i din indbakke og følge din nyhedsstrøm på Finans.",
    # L'Express, October 19
    "\nOffre limitée. 2 mois pour 1€ sans engagement\n",
    "\nJe m'abonne\n",
    # Hoff Post
    "À voir également sur le HuffPost",
    "À voir également sur Le HuffPost",
    #     Le Monde
    "Le Monde avec AFP",
    "Vous pouvez lire Le Monde sur un seul appareil à la fois",
    "Ce message s’affichera sur l’autre appareil.",
    "Découvrir les offres multicomptes",
    "Votre abonnement n’autorise pas la lecture de cet article",
    "Lecture restreinte",
    "Pour plus d’informations, merci de contacter notre service commercial.",
    #     dk
    "Artiklen fortsætter efter annoncen",
]

JUNK_COUNT_PATTERNS = (
    [
        # DA Articles
        "artiklen er opdateret kl.",
        "for abonnenter",
        "det skriver nyhedsbureauet afp.",
        "det skriver nyhedsbureauet reuters.",
        "opdateres ...",
        "artiklen fortsætter under billedet …",
        "der er ikke oplæsning af denne artikel, så den oplæses derfor med maskinstemme.",
        "kontakt os gerne på automatiskoplaesning@pol.dk, hvis du hører ord, hvis udtale kan forbedres.",
        "du kan også hjælpe ved at udfylde spørgeskemaet herunder, hvor vi spørger, hvordan du har oplevet den automatiske oplæsning.",
        "spørgeskema om automatisk oplæsning",
        "prøv politiken nu",
        "mere fra os",
        "allerede abonnent?",
        "log ind her",
        "du skal være abonnent for at lytte til denne automatiske oplæsning.",
        "køb abonnement",
        "ruslands angreb på ukraine",
        "artiklen fortsætter efter annoncen",
        "(foto: © mads claus rasmussen, ritzau scanpix)",
        "foto: jens dresling",
        "ruslands invasion af ukraine",
        "efter længere tids massiv troppeopbygning angreb rusland ukraine torsdag 24. februar 2022.",
        "en række ukrainske byer blev bombet samtidig med, at russiske soldater trængte ind i ukraine fra syd, øst og nord.",
        "artiklen fortsætter under henvisningen …",
        "hundredvis!",
        "i samfundets varetægt",
        "du har ingen artikler på din læseliste",
        "hvis du ser en artikel, du gerne vil læse lidt senere, kan du klikke på dette ikon",
        "så bliver artiklen føjet til din læseliste, som du altid kan finde her, så du kan læse videre hvor du vil og når du vil.",
        "se alle ulæste",
        "se alt du følger",
        "sådan fungerer læselisten",
        "udvælg de artikler, der interesserer dig, og opbyg din egen læseliste.",
        "så har du altid et sted at starte, når du har tid til at læse",
        "* tilføj artikler til din læseliste, * så du altid let kan finde dem igen, * ligegyldig om du er på computer eller mobil, * og læse lige når du har tid,",
        "sådan følger du",
        "følg et emne eller en skribent og vær sikker på, du får det hele med.",
        "* klik på følg ud for et tag eller en skribent, * vi kan sende dig en email, når en ny artikel udgives, * alle artikler samles i et feed på siden du følger, som du finder i højre hjørne under dit navn og i sidepanelet, * hver mandag får du en email med de mest læste artikler om det, du følger.",
        "du kan altid justere dine emails i indstillinger,",
        "næste: næste:",
        "bliv abonnent, og lyt med",
        "læs artiklen senere gemt (klik for at fjerne) læst",
        "giv artiklen videre",
        "som abonnent kan du ubegrænset dele artikler med dine venner og familie.",
        "læs mere om fordelene ved et abonnement her.",
        "redaktionen anbefaler",
        "* internationalt,",
        "om politiken",
        "organet for den højeste oplysning siden 1884",
        "rådhuspladsen 37",
        "kontakt redaktionen: 33 11 85 11",
        "kontakt kundeservice: 70 15 01 01",
        "politikens vision",
        "politikens journalistik og etik",
        "chefredaktionen",
        "christian jensen (ansvarshavende)",
        "amalie kestler",
        "digital direktør",
        "troels behrendt jørgensen",
        "kommerciel direktør",
        "astrid jørgensen",
        "digital udviklingschef",
        "marie bering",
        "digital redaktionschef",
        "thomas berndt",
        "annoncedirektør",
        "thomas hervø",
        "forsideredaktør lige nu",
        "ove kusnitzoff",
        "politiken digital",
        "politiken kombi lørdag",
        "politiken komplet",
        "kundecenter",
        "copyright politiken 2023",
        "tekst, grafik, billeder, lyd og andet",
        "indhold på dette website er",
        "beskyttet efter lov om ophavsret.",
        "politiken forbeholder sig alle",
        "rettigheder til indholdet, herunder",
        "retten til at udnytte indholdet",
        "med henblik på tekst- og",
        "datamining, jf.",
        "ophavsretslovens",
        "§ 11 b og dsm-direktivets artikel 4",
        "læs mere om ophavsret",
        "artiklen er låst – sådan kommer du videre:",
        "vil du have adgang?",
        "vil du tillade dataindsamling?",
        "som abonnent kan du tilpasse hvilken data, der indsamles.",
        "du kan altid trække dit samtykke tilbage.",
        "artiklen er føjet til din læseliste du har ulæste artikler på din læseliste",
        "log ind køb abonnement",
        "* e-avisen, * politiken live, * nyhedsbreve, * podcast, * politiken plus,",
        "* sektionerdanmarkkulturdebatklimainternationaltsportforbrug og livibyense alle,",
        "* podcastdu lytter til...madsen & magtenbogfolkkongerækkense alle,",
        "* underholdningatsbezzerwizzersudokukrydsordse alle,",
        "* andetmit politikenarkivbilletkontakt osadministrér samtykkerss feedsjobskøb abonnement,",
        "klimamonitor byrummonitor skolemonitor sundhedsmonitor kulturmonitor idrætsmonitor turistmonitor",
        "sommertilbud:spar 50% hver måned i 6 måneder",
        "læs hele samlingen →",
        "her er principperne bag ukraines store offensiv: »på papiret er der ingen tvivl om, at det er det rette sted at angribe«",
        "forstærkningerne er ankommet til den russiske skyttegrav på den anden side af marken – og de sniger sig ud om natten",
        "scenarierne er på bordet: her er fem mulige afslutninger på krigen i ukraine",
        "de ligger bare der.",
        "kolonner af togvogne fyldt med russiske lig: »der er hundredvis af lig.",
        "jeg tror ikke engang, militæret har tal på dem«",
        "»jeg beder dig forstå risikoen«, lød afslaget.",
        "en anden bekendt fra rusland har slet ikke svaret.",
        "tavsheden får det til at løbe koldt ned ad ryggen",
        "»jeg troede, jeg skulle have en god og rolig alderdom.",
        "men det her ... det ønsker jeg ikke for nogen«",
        "»vi beder ikke om, at i kommer og redder os«: en af ukraines mest jagede mænd har en særlig besked til danmark",
        "bomberne falder over ukraine og rammer civilbefolkningen.",
        "historien tegner et grusomt billede",
        "putin har flere gange truet med atomvåben.",
        "hvor langt er vi fra det utænkelige, og hvordan kan det ske?",
        "politiken i izjum: sådan ser der ud i helvede",
        "max forklarer, hvad der sker, når infanteriet sætter sig i bevægelse: »det er sådan, man undgår svære tab«",
        "en erfaren soldat ser, hvad 26-årige andriy har gang i. det giver et spjæt i soldaten, som springer hen til ambulancen",
        "ukrainsk superwoman er rasende på zelenskyj: »efter min mening begår vores regering en stor fejl«",
        "der er ikke noget, der kan forberede en på kharkivs metrostationer",
        "de er 21 år, og deres hverdag er geopolitik, tiktok, tv-serier, stinger-missiler og at grine ad fyre, der sender latterlige beskeder",
        "det, der gør størst indtryk på fotografen og mig er, at de alle virker så nervøse",
        "»nu forstår det ukrainske folk, hvad rusland er«",
        "en chokeret verden ser på billederne af det, der tyder på en russisk massakre",
        "tak for din tilmelding!",
        "vis alle nyhedsbreve her kan du læse mere om, hvordan vi håndterer dine personoplysninger.",
        "luk beskedvindue",
        "er kun for abonnenter!",
        "med et digitalt abonement får du fuld adgang til hele politiken.dk, alle nyhedsbreve og e-avisen leveret hver aften.",
        "første måned 1 kr.",
        "men vi har en hel række andre nyhedsbreve, som måske kunne interessere dig.",
        "se alle nyhedsbreve",
        "vi beklager!",
        "der skete en fejl, prøv igen senere",
        "der skete en fejl, prøv igen senere eller søg hjælp via vores kundecenter",
        "prøv 30 dage for kun 1 kr.",
        "få adgang til vores digitale univers, og læs artikler, lyt til podcasts og løs krydsord.",
        "essay: adhd plejede at være en drenge-diagnose, men nu myldrer det frem med voksne kvinder, der får diagnosen.",
        "jeg er en af dem",
        "* forbrug og liv,",
        "de har besøgt 101 spisesteder og barer det seneste år.",
        "her er alle anmeldernes højdepunkter",
        "hun er fyldt 101 år.",
        "og når hun kigger på københavn i dag, lægger hun især mærke til noget særligt ved mændene ved søerne",
        "den lille lasede pige hiver efter vejret, da hun kommer op af hullet med glimmerstenene til din mobil, makeup og elbil",
        "film og tv: guld fra arkivet",
        "'kedelig film' er verdens bedste ifølge listen, som alle filmeksperter respekterer",
        "* film og tv,",
        "politiken podcast",
        "agenterne - et liv mellem to verdener",
        "alle har hørt om samsam-sagen – vi fortæller fire andre historier fra den hemmelige verden.",
        "hvad driver agenterne, og hvorfor går det nogle gange helt galt?",
        "politiken fortæller",
        "søren ulrik thomsens øjesten er egentlig godkendt til nedrivning: »det illustrerer, hvor vigtigt dette arbejde er«",
        "* hovedstaden,",
        "inge lis troede, hun havde fundet sit livs kærlighed, men mistede 230.000 kroner.",
        "og så endte det helt galt",
        "nu fortæller matilde kimer sin side af historien: det stikker helt af for mig, da han lægger en ’løsningsmodel’ på bordet",
        "nyt nyhedsbrev: det, i taler om",
        "hver lørdag samler opinionschef lotte folke de bedste indlæg om alt det, i taler om.",
        "du er nu tilmeldt nyhedsbrevet det, i taler om.",
        "nyhedsbrevet nyt nyhedsbrev: det, i taler om er kun for abonnenter!",
        "du er allerede tilmeldt nyhedsbrevet nyt nyhedsbrev: det, i taler om",
        "dr's hovedindgange",
        "dr.dkdrtvdr lyd",
        "gå til forsiden",
        "sektionens indgange",
        "* seneste nyt, * indland, * udland, * penge, * politik, * regionalt, * vejret,",
        "mere fra dr.dk",
        "gå til forsiden af dr.dk",
        "* politik, * meningsmåling, * folketingsvalg, * folkeafstemning, * kommunal- og regionalvalg,",
        "gå til hovedindhold",
        "* abonnement,",
        "* nyheder, * blogs, * debat, * avisnyeste avis og arkivingeniørens danmarkshistoriekontakt, * fokusalle fokusprofilanalysen 2023klimamål 2030lynetteholm-projektetpfasslut med russisk gaspower-to-xmånerejsencrisprkrigens teknologinord stream-lækagenspacexspørg fagfolkettech weekly, * ida-adgang, * job, * meretip osnyhedsbreveeventpodcastemneoversigtvidensbanknavnenytapprss-feedabonnement,",
        "* abonnementervi har to typer abonnementer - plus og pro, * nyhedsbrevefå det bedste fra ing/ på mail, * ing/jobfinderlige nu ca.",
        "450 ledige job til ingeniører, tekniske specialister og it-professionelle, * eventsse og læs mere om alle vores kommende konferencer, briefings og messer, * vidensbankwhitepapers, webinarer og videnspakker, der giver dig fagligt perspektiv og inspiration til dit arbejdsliv.,",
        "digitale medier",
        "* ing/vi har kvalificeret din tech-viden siden 1892, * ing/version2den skarpeste dækning af de vigtigste it-nyheder, * ing/radarfordi tech er politisk, * ing/pronicheviden for professionelleing/buildingtechbyggeri, renovering og vedligeholding/caretechvelfærdsteknologi og hjælpemidlering/compliancetechgdpr og complianceing/datatechanalytics og dataing/digitechoffentlig digitalisering og it-projektering/gridtechenergi og elektrificeringing/mobilitytechtransport og trafiking/tech managementteknologi, forretning og ledelseing/wastetechaffald og genanvendelseing/watertechteknologi og vandets kredsløb, * transformatorugentlig podcast med teknologiske nyheder og tendenser,",
        "printmedier",
        "* ingeniørenhver anden fredag, * tech managementstyrk ledelsen af den teknologiske transformation - magasin 2 gange om året,",
        "kommercielt",
        "* tech relationsteknologiens b2b branding- og kommunikationsbureau, * ing/peopletechom rekruttering og fastholdelse af tekniske specialister., * teknologiens mediehusvi bygger bro med stærke vidensmedier, relevante events, nærværende netværk og ing/jobfinder hvor vi forbinder kandidater og virksomheder.,",
        "har du feedback eller brug for teknisk hjælp kan du skrive til vores support.",
        "bliv abonnent",
        "chevron_left",
        "chevron_right",
        "plus-abonnement",
        "dit medlemskab giver adgang",
        "som medlem af ida har du gratis adgang til plus-indhold, som en del af dit medlemskab.",
        "fortsæt med mitida for at aktivere din adgang til indholdet.",
        "fortsæt med mitida",
        "oplever du problemer med login, så skriv til os på websupport@ing.dk",
        "abonnementsfordele",
        "fuld adgang til ing.dk, version2 og radar",
        "fuld digital adgang til plus-indhold på ing.dk, version2 og radar, tilgængeligt på din computer, tablet og mobil.",
        "kuraterede nyhedsbreve",
        "det seneste nye fra branchen, leveret til din indbakke.",
        "adgang til debatten",
        "deltag i debatten med andre kloge læsere.",
        "ingen kommentarer endnu.",
        "start debatten",
        "* facebook, * twitter, * linkedin, * emaile-mail, * linkkopier link,",
        "ing/jobfinderchevron_right",
        "opret jobannonce",
        "er det dig?",
        "log ind eller opret en bruger for at deltage i debatten.",
        "settingsdebatvisning",
        "* sortér efter chevron_rightthumb_upbedstewb_sunnynyestehistoryældste, * trådet debat,",
        "om teknologiens mediehus",
        "vi bygger bro med stærke vidensmedier, relevante events, nærværende netværk og teknologiens jobfinder, hvor vi forbinder kandidater og virksomheder.",
        "mere om teknologiens mediehus",
        "abonnement & nyhedsbreve",
        "læs her om vores forskellige abonnementstyper",
        "med vores nyhedsbreve får du et fagligt overblik og adgang til levende debat mellem fagfolk.",
        "annoncering",
        "teknologiens mediehus tilbyder en bred vifte af muligheder for annoncering over for ingeniører og it-professionelle.",
        "hvad kan vi tilbyde?",
        "tech relations leverer effektiv formidling af dit budskab til ingeniører og it-professionelle.",
        "ing/jobfinder",
        "danmarks største jobplatform for ingeniører, it-professionelle og tekniske specialister.",
        "* find job, * indryk job, * kontakt salg,",
        "kalvebod brygge 33, 1560 københavn v",
        "adm. direktør christina blaagaard collignon",
        "chefredaktør trine reitz bjerregaard",
        "kontakt redaktionen",
        "* om, * kontakt, * vores politikker, * priser og abonnementsbetingelser, * annoncer hos os, * cookiedeklaration,",
        "© 1994 - 2023 teknologiens mediehus",
        "* more_vertinsert_linkkopier link,",
        "»om aftenen er det, som om det går op for mig, at irma lukker.",
        "jeg sover normalt virkelig godt, men jeg kan ikke sove, jeg ligger bare«",
        "det meste er opfanget af bakkegårdens overvågningskameraer: vikarerne hilser på de indsatte som venner.",
        "og så stikker det helt af",
        "niels holst",
        "det er ikke første verdenskrig – men det ligner",
        "jeppe dong abrahamsen",
        "* den levendehenter...49:47manden: »vi står midt i en manderevolution«, * poptillæggethenter...56:28ingen kan forene hjertesorg, queervrede og klimakrise, som anohni gør, * du lytter til politikenhenter...30:4611. august: hiphop fylder 50 år – hvad fuck fejrer vi?, * du lytter til politikenhenter...27:2510. august: kan biden hjælpe de sorte uden at snyde de hvide?,",
        "eva holtegaard-kasler",
        "* meme dig til magtenhenter...33:35meme dig til magten: farvel syg arbejdskultur, hello #lazygirljobbliv abonnent, og lyt meddu skal være abonnent for at lytte til denne automatiske oplæsning.køb abonnementallerede abonnent?",
        "login, * poptillæggethenter...63:55ingen ved, om de skal elske eller hade 'and just like that', * du lytter til politikenhenter...28:3018. august: digital dopamin: derfor kan du ikke styre dit skærmforbrug, * den levendehenter...49:26magt: »magt er overalt og næsten umulig at få greb om«bliv abonnent, og lyt meddu skal være abonnent for at lytte til denne automatiske oplæsning.køb abonnementallerede abonnent?",
        "* sport, * vm atletik, * live, * resultater, * features,",
        "om måneden.",
        "sidste chance: spar 50% hver måned i 6 måneder",
        "* du lytter til politikenhenter...23:4325. august: trump: elefanten, der ikke er i rummet, * valgethenter...16:06er der nogen, der ved, hvor de har ellemann?bliv abonnent, og lyt meddu skal være abonnent for at lytte til denne automatiske oplæsning.køb abonnementallerede abonnent?",
        "login, * den levendehenter...44:30vrede kvinder: »jeg ser vreden som nogle naturlige grænser, vi har«, * du lytter til politikenhenter...32:5924. august: rumrejsen: andreas og de sære ritualer,",
        "den anden stak af.",
        "login, * bogfolkhenter...42:45karoline stjernfelt: »det har både været enormt gavnligt og enormt skadeligt med den opmærksomhed, kroppen har fået gennem sociale medier«bliv abonnent, og lyt meddu skal være abonnent for at lytte til denne automatiske oplæsning.køb abonnementallerede abonnent?",
        "login, * du lytter til politikenhenter...23:231. september: hvorfor har vi ikke fri hash i danmark?, * valgethenter...16:40nu gør vanopslagh sig lækker for en jysk tømrermesterbliv abonnent, og lyt meddu skal være abonnent for at lytte til denne automatiske oplæsning.køb abonnementallerede abonnent?",
        "* meme dig til magtenhenter...32:18meme dig til magten: derfor har en klapstol oversvømmet internettetbliv abonnent, og lyt meddu skal være abonnent for at lytte til denne automatiske oplæsning.køb abonnementallerede abonnent?",
        "få adgang til artikler på jp.dk",
        "prøv 3 måneder for 99 kr.",
        "få adgang nu",
        "v/betaling med kreditkort el.",
        "fortsætter automatisk som løbende abonnement til 99 kr.",
        "fortrydelsesret i medfør af forbrugeraftaleloven.",
        "*fast intropris for 3 mdr.",
        "til nye kunder, der ikke har været kunder hos jyllands-posten de seneste seks mdr.",
        "måned efter de første 3 mdr.",
        "kan opsiges med 1 dags varsel til udløb af introduktionsperioden.",
        "mindstepris for 3 mdr.",
        "læs artiklen senere\n          gemt (klik for at fjerne)\n          læst",
        "fortsætter herefter til 99 kr.",
        "fortrydelsesret jf.",
        "forbrugeraftaleloven.",
        "\læs også",
    ]
    + [  # German Patterns
        "folgen ich folge",
        "mehr zum thema 1/",
        "der überblick.",
        "bild: reuters",
        "ein gastbeitrag.",
        "bild: picture alliance",
        "sie können den artikel leider nicht mehr aufrufen.",
        "der link, der ihnen geschickt wurde, ist entweder älter als 30 tage oder der artikel wurde bereits 10 mal geöffnet.",
        "digital-abo",
        "sagen, was ist.",
        "testen sie das digitale angebot und erfahren sie, warum mehr als 400.000 menschen den spiegel abonnieren.",
        "kennenlernangebot - 4 wochen für € 1,–",
        "jetzt abonnieren",
        "ihre bezahlmöglichkeiten:",
        "jederzeit kündigen.",
        "mehr perspektiven, mehr verstehen.",
        "freier zugang zu allen artikeln, videos, audioinhalten und podcasts",
        "alle artikel auf spiegel.de frei zugänglich",
        "der spiegel als e-paper und in der app",
        "alle artikel zum anhören und exklusive podcasts",
        "nur € 21,99 pro monat, jederzeit kündbar",
        "sie haben bereits ein digital-abonnement?",
        "spiegel+ wird über ihren itunes-account abgewickelt und mit kaufbestätigung bezahlt.",
        "in den einstellungen ihres itunes-accounts können sie das abo jederzeit kündigen.",
        "um spiegel+ außerhalb\ndieser app zu nutzen, müssen sie das abo direkt nach dem kauf mit einem spiegel-id-konto verknüpfen.",
        "mit dem kauf akzeptieren sie unsere\nallgemeinen geschäftsbedingungen und datenschutzerklärung.",
        "zum inhalt springen",
        "der spiegel wirtschaft",
        "abonnement abo anmelden",
        "* e-mail, * messenger, * whatsapp,",
        "spiegel plus anmelden",
        "ihre bezahlmöglichkeiten: paypal sepa visa mastercard applepay googlepay",
        "weiterlesen mit spiegel+",
        "* alle artikel auf spiegel.de frei zugänglich, * der spiegel als e-paper und in der app, * alle artikel zum anhören und exklusive podcasts, * nur € 21,99 pro monat, jederzeit kündbar, * nur € 19,99 pro monat, jederzeit kündbar,",
        "24 stunden vor ablauf verlängert sich das abo automatisch um einen monat zum preis von zurzeit 19,99€.",
        "um spiegel+ außerhalb dieser app zu nutzen, müssen sie das abo direkt nach dem kauf mit einem spiegel-id-konto verknüpfen.",
        "mit dem kauf akzeptieren sie unsere allgemeinen geschäftsbedingungen und datenschutzerklärung.",
        "kostenlose online-spiele",
        "mehr spiele",
        "* kreuzworträtsel, * solitär, * sudoku, * mahjong, * bubble-shooter, * jackpot, * snake, * exchange, * 2048, * doppel, * rushtower, * sudoken, * street, * wortblitz, * fibonacci, * gumblast, * wimmelbild, * skiracer, * trivial pursuit,",
        "serviceangebote von spiegel-partnern",
        "ebay gutscheine",
        "christ gutscheine",
        "expedia gutscheine",
        "tink gutscheine",
        "top gutscheine alle shops",
        "* bußgeldrechner, * firmenwagenrechner,",
        "* brutto-netto-rechner, * jobsuche, * kurzarbeitergeld-rechner, * studienfächer erklärt,",
        "* gehaltsvergleich, * immobilienbewertung, * studium und finanzen, * versicherungen, * währungsrechner,",
        "* bücher bestellen, * eurojackpot, * ferientermine,",
        "* glücksspirale, * gutscheine, * lotto 6aus49,",
        "* seniorenportal, * spiele, * das tägliche quiz,",
        "alle magazine des spiegel",
        "* der spiegel, * spiegel geschichte, * spiegel wissen, * spiegel start, * spiegel geld, * spiegel coaching, * spiegel chronik, * spiegel spezial, * dein spiegel, * spiegel edition, * spiegel bestseller, * s-magazin, * spiegel leben, * spiegel biografie,",
        "spiegel gruppe",
        "abo abo kündigen shop manager magazin harvard business manager buchreport werbung jobs manufaktur spiegel akademie spiegel ed",
        "impressum datenschutz nutzungsbedingungen teilnahmebedingungen cookies & tracking newsletter kontakt hilfe text- & nutzungsrechte",
        "facebook twitter wo sie uns noch folgen können",
        "die wiedergabe wurde unterbrochen.",
        "teilen sie ihre meinung mit",
        "melden sie sich an und diskutieren sie mit",
        "speichern sie ihre lieblingsartikel in der persönlichen merkliste, um sie später zu lesen und einfach wiederzufinden.",
        "anmelden oder konto erstellen",
        "mehrfachnutzung erkannt",
        "bitte beachten sie: die zeitgleiche nutzung von spiegel+-inhalten ist auf ein gerät beschränkt.",
        "wir behalten uns vor, die mehrfachnutzung zukünftig technisch zu unterbinden.",
        "sie möchten spiegel+ auf mehreren geräten zeitgleich nutzen?",
        "zu unseren angeboten",
        "der spiegel politik",
        "mehr lesen über",
        "verwandte artikel",
        "mister spex gutscheine",
        "lampenwelt gutscheine",
        "conrad gutscheine",
        "belvini gutscheine",
        "speichern sie audioinhalte in ihrer playlist, um sie später zu hören oder offline abzuspielen.",
        "zusätzlich können sie ihre playlist über alle geräte mit der spiegel-app synchronisieren, auf denen sie mit ihrem konto angemeldet sind.",
        "der spiegel panorama",
        "h&m gutscheine",
        "thalia gutscheine",
        "foot locker gutscheine",
        "sephora gutscheine",
        "mehr zum thema",
        "empfohlener externer inhalt",
        "an dieser stelle finden sie einen externen inhalt von twitter, der den artikel ergänzt und von der redaktion empfohlen wird.",
        "sie können ihn sich mit einem klick anzeigen lassen und wieder ausblenden.",
        "externer inhalt",
        "ich bin damit einverstanden, dass mir externe inhalte angezeigt werden.",
        "damit können personenbezogene daten an drittplattformen übermittelt werden.",
        "mehr dazu in unserer datenschutzerklärung.",
        "zur datenschutzerklärung",
        "artikel zum hören•2 min",
        "der spiegel ausland",
        "booking gutscheine",
        "eis.de gutscheine",
        "hellofresh gutscheine",
        "otto gutscheine",
        "der spiegel sport",
        "adidas gutscheine",
        "asos gutscheine",
        "nike gutscheine",
        "lidl gutscheine",
        "startseite home : 0 neue oder aktualisierte artikel.",
        "* inland, * ausland, * politische bücher, * geschichte, * briefe an die herausgeber,",
        "* historische hyperinflation, * digitec, * unternehmen, * wohnen, * auto & verkehr, * klima & nachhaltigkeit, * arm und reich, * schneller schlau, * wirtschaftswissen,",
        "* accenture: wandel gestalten,",
        "* meine finanzen, * finanzmarkt, * börsen & märkte,",
        "* mein depot, * börsenlexikon, * börsenspiel, * die digitale zukunft finanzieren,",
        "* debatten, * bücher, * medien, * kino, * pop, * bühne und konzert, * kunst und architektur, * kunstmarkt, * familie, * tv- & radioprogramm,",
        "karriere & hochschule",
        "* büro & co, * hörsaal, * klassenzimmer, * die karrierefrage,",
        "* fußball, * frauenfußball-wm, * formel 1, * mehr sport, * rhein-main-sport, * sportpolitik, * sport-tipps, * sport live, * sport-ergebnisse,",
        "gesellschaft",
        "* menschen, * kriminalität, * unglücke, * gesundheit, * tiere, * smalltalk, * jugend schreibt,",
        "* bierkultur, * mit tempo in die digitale zukunft,",
        "* mode & design, * essen & trinken, * leib & seele, * trends & nischen, * quarterly,",
        "* frankfurt, * region und hessen, * wirtschaft, * kultur, * sport, * f.a.z.",
        "leser helfen,",
        "* veranstaltungen,",
        "technik & motor",
        "* motor, * elektromobilität, * technik, * digital, * energie,",
        "* medizin & ernährung, * krebsmedizin, * weltraum, * leben & gene, * erde & klima, * physik & mehr, * archäologie & altertum, * geist & soziales, * forschung & politik, * ab in die botanik, * netzrätsel,",
        "* wetter, * winterthur, * f.a.z.",
        "leserreisen,",
        "agenturmeldungen",
        "datenschutz",
        "nutzungsbedingungen",
        "aktuelle nachrichten aus politik, wirtschaft, sport und kultur",
        "herausgegeben von gerald braunberger, jürgen kaube, carsten knop, berthold kohler",
        "zeitung faz.net",
        "bildbeschreibung einblenden",
        "quelle: f.a.z.",
        "hier können sie die rechte an diesem artikel erwerben.",
        "zur startseite",
        "weitere themen",
        "ähnliche themen",
        "topmeldungen",
        "immer auf dem laufenden sie haben post!",
        "die wichtigsten nachrichten direkt in ihre mailbox.",
        "sie können bis zu 5 newsletter gleichzeitig auswählen es ist ein fehler aufgetreten.",
        "bitte versuchen sie es erneut.",
        "vielen dank für ihr interesse an den f.a.z.-newslettern.",
        "sie erhalten in wenigen minuten eine e-mail, um ihre newsletterbestellung zu bestätigen.",
        "administrative managing director (m|f|d)",
        "gsi helmholtzzentrum für schwerionenforschung gmbh",
        "administrative*r geschäftsführer*in (m|w|d)",
        "über dr. maier + partner gmbh executive search",
        "zum stellenmarkt",
        "verlagsangebot",
        "* douglas-rabattcode,",
        "* parfumdreams-gutschein,",
        "* flaconi-gutschein,",
        "* parfümerie pieper-rabattcode,",
        "* sephora-rabattcode,",
        "* notino-rabattcode,",
        "* mac-gutschein,",
        "* niche beauty-rabattcode,",
        "* e-bike-test,",
        "* powerbank-test,",
        "* inhalator-test,",
        "* fensterputzroboter,",
        "* abo-service, * best ager, * selection shop, * firmen, * finanz-services, * tarifrechner, * newsletter, * immobilien- markt, * testberichte, * stellenmarkt, * spiele, * gutscheine, * veranstaltungen, * sport-ergebnisse, * tv-programm, * wetter,",
        "frankfurter allgemeine zeitung",
        "* datenschutz, * cookie-manager, * einwilligung widerrufen, * werbefrei lesen, * nutzungsbedingungen,",
        "* kontakt, * abo-angebote, * mediadaten,",
        "* redaktion, * vertrauen, * über die f.a.z.,",
        "* stellenmarkt, * tarifrechner, * immobilienmarkt,",
        "* presse, * themen wirtschaft, * blogs, * impressum,",
        "© frankfurter allgemeine zeitung gmbh 2001 - 2023 alle rechte vorbehalten.",
        "beitrag per e-mail versenden",
        "ein fehler ist aufgetreten.",
        "bitte überprüfen sie ihre eingaben.",
        "vielen dank der beitrag wurde erfolgreich versandt.",
        "zugang zu allen f+ artikeln 2,95 € / woche jetzt 30 tage kostenfrei testen 2,95 € / woche jetzt kostenfrei zugang abonnieren?",
        "mit einem klick online kündbar",
        "weiter ja, 30 tage kostenfrei testen",
        "diese und viele weitere artikel lesen sie mit f+",
        "* maybrit illner, * tatort, * ferdinand von schirach,",
        "* julian assange, * anne will, * new york times, * banksy,",
        "* peter handke, * hart aber fair, * gez, * jan böhmermann,",
        "* michel houellebecq, * bushido, * richard david precht, * claas relotius,",
        "* haruki murakami, * astrid lindgren, * lady gaga, * attila hildmann,",
        "* the north face-gutschein,",
        "* radonline-gutschein,",
        "* rose bikes-gutschein,",
        "* groupon-gutschein,",
        "* decathlon-gutschein,",
        "* jack wolfskin-gutschein,",
        "* mydays-gutschein,",
        "* bike24-gutschein,",
        "* kinderwagen-test,",
        "* av-receiver-test,",
        "* luftbefeuchter-test,",
        "* trinkflaschen-test,",
        "* presse, * themen feuilleton, * blogs, * impressum,",
        "* küchenwaage-test,",
        "* wassersprudler-test,",
        "* windeleimer-test,",
        "* toaster-test,",
        "* presse, * themen gesellschaft, * blogs, * impressum,",
        "lesermeinungen",
        "* saturn-gutschein,",
        "* amazon-gutschein,",
        "* gopro-aktionscode,",
        "* hp store-gutschein,",
        "* grover-gutschein,",
        "* samsung-gutscheincode,",
        "* ebay-gutschein,",
        "* kitchenaid-gutschein,",
        "* wlan-repeater-test,",
        "* laserdrucker-test,",
        "* internetradio-test,",
        "* espressomaschine-test,",
        "* presse, * politik themen, * blogs, * impressum,",
        "* westwing-gutschein,",
        "* wayfair-rabattcode,",
        "* massivmoebel24-gutschein,",
        "* maisons du monde-gutschein,",
        "* otto-gutschein,",
        "* poco-gutschein,",
        "* lampenwelt-gutschein,",
        "* tchibo-gutschein,",
        "* vaay-rabattcode,",
        "* sanicare-gutschein,",
        "* docmorris-gutschein,",
        "* foodspring-gutschein,",
        "* myprotein-gutschein,",
        "* shop apotheke-gutschein,",
        "* lensbest-gutschein,",
        "* medpex-gutschein,",
        "* wanderstöcke-test,",
        "* fahrrad-navi-test,",
        "* damen-wanderschuhe,",
        "* fitnessband-test,",
        "* presse, * sport themen, * blogs, * impressum,",
        "permalink: https://www.faz.net/-gpf-bbvzq",
        "janina käppel",
        "twitter.com",
        "link kopieren",
        "share on facebook",
        "share on twitter",
        "share via email",
        "philipp johannßen",
        "martin franke",
        "tickaroolive blog software",
        "* veröffentlicht/aktualisiert:,",
        "quelle: faz.net",
        "artikel zum hören•3 min",
        "cyberport gutscheine",
        "personalleitung (m/w/d)",
        "quelle: dpa",
        "artikel auf einer seite lesen",
        "anna-lena ripperger",
        "mitarbeiter (m/w/d) studienberatung & sales frankfurt am main",
        "fom hochschule für oekonomie & management gemeinnützige gesellschaft mbh",
        "vanessa angermann",
        "* twitter, * facebook, * e-mail, * messenger, * whatsapp,",
        "zur ausgabe",
        "anna schiller",
        "jannik müller",
        "über fricke finance & legal",
        "nicolas kurzawa",
        "othmara glas",
        "katharina moser",
        "henrik bahlmann",
        "* mit tempo in die digitale zukunft,",
        "* wetter, * bis tief in polare gebiete, * winterthur, * f.a.z.",
        "klaus bardenhagen",
        "simon hüsgen",
        "sven scharf",
        "gregor grosse",
        "* fußball, * frauenfußball-wm, * formel 1, * mehr sport, * leichtathletik-wm, * rhein-main-sport, * sportpolitik, * sport-tipps, * sport live, * sport-ergebnisse,",
        "simon röhricht",
        "stefanie sommer",
        "* fußball, * frauenfußball-wm, * formel 1, * mehr sport, * leichtathletik-wm, * us open, * rhein-main-sport, * sportpolitik, * sport-tipps, * sport live, * sport-ergebnisse,",
        "* alle artikel auf spiegel.de frei zugänglich, * der spiegel als e-paper und in der app, * alle artikel zum anhören und exklusive podcasts, * nur € 21,99 pro monat, jederzeit kündbar,",
        "24 stunden vor ablauf verlängert sich das abo automatisch um einen monat zum preis von zurzeit € 21,99.",
        "fabian drahmoune",
        "mathias peer",
        "* debatten, * bücher, * unsere reisebegleiter, * medien, * kino, * pop, * bühne und konzert, * kunst und architektur, * kunstmarkt, * familie, * tv- & radioprogramm,",
        "* inspiration für den lebensraum küche,",
        "* der spiegel, * spiegel geschichte, * spiegel wissen, * spiegel start, * spiegel geld, * spiegel coaching, * spiegel chronik, * dein spiegel, * spiegel bestseller, * s-magazin, * spiegel edition, * spiegel spezial, * spiegel biografie,",
        "* der spiegel, * spiegel spezial, * spiegel geschichte, * spiegel wissen, * spiegel start, * spiegel geld, * spiegel coaching, * dein spiegel, * spiegel bestseller, * s-magazin, * spiegel edition, * spiegel biografie, * spiegel chronik,",
        "€ 2,99 pro woche für 52 wochen",
        "€ 100,- sparen",
        "24 stunden vor ablauf verlängert sich das abo automatisch um\neinen monat zum preis von zurzeit € 21,99.",
        "optensteinen, charlene",
        "sie können ihre zustimmung jederzeit wieder zurücknehmen.",
        "irem yildirim",
        "oliver kühn",
        "philipp von reinersdorff",
        "zugang zu allen faz+ beiträgen\n    11,80\xa0€\n    jetzt nur 0,99\xa0€",
        "jetzt zugang 11,80\xa0€ für nur 0,99\xa0€ abonnieren?",
        "externer inhalt von youtube",
        "um externe inhalte anzuzeigen, ist ihre widerrufliche zustimmung nötig.",
        "dabei können personenbezogene daten von drittplattformen (ggf.",
        "usa) verarbeitet werden.",
        "weitere informationen .",
        "zum jubiläum: 7 monate für nur 5 € pro monat testen",
        "zum jubiläum: 7 monate für nur  5 € pro monat testen",
        "malte müller-michaelis",
    ]
    + [  # French Patterns
        "inscrivez-vous à notre newsletter.",
        "musique et habillage : emmanuel herschon/studio torrent",
        "logo : anne-laure chapelain/benjamin chazal",
        "comment écouter un podcast ?",
        "suivez le guide.",
        "pour aller plus loin",
        "retrouvez tous les episodes de la loupe",
        "vous avez refusé les cookies associés aux contenus issus de tiers en vous abonnant.",
        "vous ne pourrez donc pas lire nos vidéos qui ont besoin de cookies tiers pour fonctionner.",
        "vous utilisez un bloqueur de publicité.",
        "nous vous conseillons de le désactiver afin d’accéder à nos vidéos.",
        "si vous n'êtes dans aucun de ces deux cas, contactez-nous à aide@huffingtonpost.fr vous ne pouvez pas visionner ce contenu car :",
        "à voir également sur le huffpost :",
        "photo presse",
        "nos réponses.",
        "la rédaction du figaro n‘a pas participé à la réalisation de cet article.",
        "la rédaction du figaro n'a pas participé à la réalisation de cet article.",
        "certains liens sont trackés et peuvent générer une commission pour le figaro.",
        "contenu conçu et proposé par",
        "contenu conçu et proposé par le figaro services.",
        "les prix mentionnés dans cet article le sont à titre indicatif et sont susceptibles d’évoluer.",
        "les prix mentionnés dans cet article le sont à titre indicatif.",
        "lorsque vous achetez via nos liens de vente, nous pouvons percevoir une commission d’affiliation.",
        "bertrand guay / afp",
        "alain jocard / afp",
        "geoffroy van der hasselt / afp",
        "thomas samson / afp",
        "aller au contenu",
        "lire le journal",
        "vente flash -70% pendant 1 an",
        "* lien copié, * mail, * facebook, * twitter, * linkedin, * messenger, * whatsapp,",
        "la rédaction vous conseille",
        "aucun commentaire",
        "il n'y a actuellement aucun commentaire concernant cet article.",
        "soyez le premier à donner votre avis !",
        "à lire aussi",
        "plus de services",
        "l'actualité à ne pas manquer",
        "* résultats des élections, * covid-19, * guerre en ukraine, * tension iran-etats unis, * corée-du-nord, * actualité politique en temps réel, * analyses, débats politiques et sociétaux, * actualité et réseaux sociaux,",
        "programme tv",
        "* programme tv ce soir, * programme tv en ce moment, * programme tv tnt, * séries netflix, hbo, ocs et tv, * election et photos miss france, * programme tv canalsat, * programme tv free, * programme tv sfr, * actu people,",
        "* calendriers et résultats des matchs en direct, * coupe du monde de rugby 2023, * jeux olympiques, * actualité cyclisme, * résultats, classement général tour de france, * qualifications euro 2024, * classement ligue 1, * classement top 14, * transferts football, * coupe du monde 2022, * ballon d'or france football,",
        "* horoscope du jour, * guide du mariage, * recettes de cuisine, * brigitte macron, * actu mode, * apéritif dînatoire, * recette pâte à crêpe, * tendance bijoux, * meghan markle, * gainer son corps,",
        "* fiches et guides des médicaments, * astuces et conseils bien-être, * santé et sexualité, * index des maladies, * conseils alimentation, nutrition et santé, * l'encyclopédie des organes, * conseils en psychologie, * la pollution va t-elle nous tuer ?, * apnée du sommeil : comment mieux dormir ?, * 15 mythes sur les vertus des aliments,",
        "guide d'achat",
        "* guide d'achat maison et jardin, * guide d'achat santé et beauté, * guide d’achat high-tech, * guide d'achat smartphones et tablettes, * comment choisir le meilleur extracteur de jus ?, * quelle est la meilleure montre connectée ?, * quel est le meilleur home cinéma sans fil ?, * comparatif semelle gel, * quel épilateur électrique choisir ?, * bons plans,",
        "éducation et orientation",
        "* résultats bac, * révisions du bac, * parcoursup, * annuaire des écoles de commerce, * les entreprises qui recrutent, * trouver un stage, * résultats brevet des collèges, * classement des écoles de commerce, * trouver une alternance, * agenda étudiant : jpo, salons...,",
        "* succession de johnny hallyday, * sorties cinéma, * guide arts et expositions, * actualité musicale, * actualité jeux-vidéo, * citations et proverbes, * réservation de spectacles et théâtre, * sortir à paris, * histoire de france, * langue française,",
        "codes promos et réductions",
        "* code promo wish, * code promo cdiscount, * code promo shein, * code promo ebay, * code promo aliexpess, * code promo deliveroo, * code promo nike, * code promo sephora, * code promo showroomprive, * code promo asos,",
        "offres d'emploi",
        "* toutes les offres d'emploi, * emploi à paris, * emploi à lyon, * emploi à toulouse, * emploi à nantes, * emploi à bordeaux, * emploi commercial, * emploi contrôleur de gestion, * emploi logistique, * emploi communication, * nos fiches métiers,",
        "annonces immobilières",
        "* annonces immobilières, * achat appartement paris, * achat appartement nice, * achat appartement cannes, * achat appartement bordeaux, * achat appartement lyon, * achat appartement aix-en-provence, * achat maison bordeaux, * achat maison marseille, * achat maison montpellier,",
        "économie argent et finances",
        "* simulateur de seuil de richesse, * actualité économique et analyses, * impôts sur le revenu : simulateur, * palmarès des villes où investir dans l'immobilier, * studios et 2-pièces : les loyers ville par ville, * calculer l'impôt à payer, * barême des droits de succession et donation, * indice de référence des loyers (irl), * en france, les hauts revenus sont-ils tous des «riches»?, * carte familles nombreuses : jusqu’à 75 % de réduction sur les billets de train,",
        "* guide des croisières, * guide voyage jordanie, * guide voyage namibie, * guide voyage maroc, * guide voyage new york, * guide voyage birmanie, * guide voyage lille, * guide voyage antilles, * guide voyage japon, * guide voyage amsterdam,",
        "les magazines figaro",
        "* le figaro magazine, * madame figaro, * le figaro, * le figaro hors-série, * le figaro histoire, * tv magazine, * f, l'art de vivre,",
        "figaro services",
        "* scpi de rendement, * changer d’assurance de prêt immobilier, * le village de l'emploi avis, * alarme maison, * demande de carte grise en ligne, * définition du portage salarial, * stress et troubles du sommeil, * a savoir en france, * annonces légales,",
        "* primeurs, * comprendre le vin, * tops et sélections, * domaines et vignerons, * economie du vin, * foire aux vins, * magazine du vin, * spititueux, * cocktails et mixologie, * terroir et viticulture,",
        "résultats des élections par département",
        "* résultats des élections hauts-de-seine, * résultats des élections seine-saint-denis, * résultats des élections val-de-marne, * résultats des élections val-d'oise, * résultats des élections yvelines, * résultats des élections var, * résultats des élections alpes-maritimes, * résultats des élections essonne, * résultats des élections nord,",
        "résultats des élections par région",
        "* résultats des élections auvergne-rhône-alpes, * résultats des élections bourgogne-franche-comté, * résultats des élections bretagne, * résultats des élections centre-val de loire, * résultats des élections corse, * résultats des élections grand est, * résultats des élections hauts-de-france, * résultats des élections ile-de-france, * résultats des élections normandie, * résultats des élections nouvelle-aquitaine, * résultats des élections occitanie, * résultats des élections pays de la loire, * résultats des élections provence-alpes-côte d'azur,",
        "résultats des élections par ville",
        "* résultats des élections paris, * résultats des élections marseille, * résultats des élections lyon, * résultats des élections toulouse, * résultats des élections nice, * résultats des élections nantes, * résultats des élections montpellier, * résultats des élections strasbourg, * résultats des élections bordeaux, * résultats des élections lille, * résultats des élections rennes, * résultats des élections reims, * résultats des élections saint-étienne,",
        "le figaro : editions locales",
        "* le figaro bordeaux, * le figaro lyon, * le figaro nantes, * le figaro nice,",
        "suivez l’actu en temps réelavec l’application le figaro",
        "vous avez choisi de refuser les cookies",
        "et pourtant, la publicité personnalisée est un moyen de soutenir le travail de notre rédaction qui s’engage à vous proposer chaque jour une information de qualité.",
        "en acceptant les cookies, vous pourrez accéder aux contenus et fonctionnalités gratuites que propose notre site.",
        "à tout moment, vous pouvez modifier vos choix via le bouton “paramétrer les cookies” en bas de page.",
        "ourefuser et s'abonner",
        "partager via :",
        "* mail, * facebook, * twitter, * whatsapp, * lien copié, * messenger,",
        "plus d'options",
        "nos liens utiles",
        "* nos applications mobiles, * les vidéos figaro live, * les podcasts du figaro, * les programmes tv, * les résultats sportifs, * carnet du jour, * figaro store, * le figaro bordeaux, * le figaro lyon, * le figaro nantes, * le figaro nice,",
        "lire ce numéro",
        "* découvrez toutes les offresles articles en illimité à partir de 0,99€ sans engagement, * gérer votre abonnement, * espace personnel,",
        "applications mobiles",
        "* le figaro : iphone | android, * le figaro jeux : iphone | android, * le kiosque le figaro : iphone | android, * le figaro cuisine : iphone | android,",
        "nos newsletters",
        "inscrivez-vous aux newsletters",
        "suivez-nous sur :",
        "* plan du site, * confidentialité, * cgu, * cgv, * info cookies, * charte, * aide et contact, * mentions légales, * abonnements, * newsletter, * publicité, * sitemap,",
        "regarder la vidéo",
        "à découvrir",
        "consulter le journal",
        "le monde - retour à la une",
        "se connecter se connecter s’abonner dès 5,49 €/mois",
        "temps de lecture 2 min.",
        "* ajouter à vos sélectionsajouter à vos sélectionspour ajouter l’article à vos sélections identifiez-vouss’inscrire gratuitementvous possédez déjà un compte ?",
        "se connecter, * partagerpartager sur facebookenvoyer par e-mailpartager sur whatsapppartager sur linkedin,",
        "l’espace des contributions est réservé aux abonnés.",
        "abonnez-vous pour accéder à cet espace d’échange et contribuer à la discussion.",
        "édition du jour",
        "lire le journal numérique",
        "culture générale",
        "des leçons interactives par la rédaction pour tester vos connaissances.",
        "mots croisés",
        "découvrez chaque jour une nouvelle grille de mots croisés.",
        "le monde ateliers",
        "cours du soir",
        "cours en ligne, cours du soir, ateliers : développez vos compétences",
        "lecture du monde en cours sur un autre appareil.",
        "vous pouvez lire le monde sur un seul appareil à la fois",
        "ce message s’affichera sur l’autre appareil.",
        "découvrir les offres multicomptes",
        "* parce qu’une autre personne (ou vous) est en train de lire le monde avec ce compte sur un autre appareil.vous ne pouvez lire le monde que sur un seul appareil à la fois (ordinateur, téléphone ou tablette)., * comment ne plus voir ce message ?en cliquant sur « » et en vous assurant que vous êtes la seule personne à consulter le monde avec ce compte., * que se passera-t-il si vous continuez à lire ici ?ce message s’affichera sur l’autre appareil.",
        "ce dernier restera connecté avec ce compte., * y a-t-il d’autres limites ?non.",
        "vous pouvez vous connecter avec votre compte sur autant d’appareils que vous le souhaitez, mais en les utilisant à des moments différents., * vous ignorez qui est l’autre personne ?nous vous conseillons de modifier votre mot de passe.,",
        "lecture restreinte",
        "votre abonnement n’autorise pas la lecture de cet article",
        "pour plus d’informations, merci de contacter notre service commercial.",
        "* les ateliers du monde, * mémorable : travailler sa mémoire, * mots croisés / sudokus, * résultats élections, * education, * gastronomie,",
        "* les meilleures imprimantes laser, * les meilleurs aspirateurs robots, * jeux de société pour adultes,",
        "* codes promo, * black friday, * soldes,",
        "* le monde in english, * algérie, * belgique, * canada, * côte d’ivoire, * mali, * maroc, * sénégal, * suisse, * tunisie,",
        "* découvrir le jardinage, * hits du moment, * formation professionnelle,",
        "* le monde evènements, * courrier international, * télérama, * la vie, * le huffpost, * l’obs, * le monde diplomatique, * la société des lecteurs du monde, * talents, * source sûre, * le club de l’économie, * m publicité, * le carnet du monde,",
        "newsletters du monde",
        "recevoir les newsletters du monde",
        "* sur iphone, * sur android,",
        "archives du monde s’abonner se connecter consulter le journal du jour évenements abonnés jeux-concours abonnés contacter le monde",
        "* mentions légales, * conditions générales, * charte du groupe, * politique de confidentialité, * aide (faq),",
        "* mentions légales, * charte du groupe, * politique de confidentialité, * gestion des cookies, * conditions générales, * aide (faq),",
        "suivez le monde",
        "* facebook, * youtube, * twitter, * instagram, * snapchat, * fils rss,",
        "ajouter à vos sélections",
        "pour ajouter l’article à vos sélections identifiez-vous",
        "s’inscrire gratuitement",
        "vous possédez déjà un compte ?",
        "se connecter",
        "nos guides d’achat",
        "services le monde",
        "testez votre culture générale avec la rédaction du monde",
        "mots croisés, sudoku, mots trouvés... jouez avec nous",
        "gagnez du temps avec notre sélection des meilleurs produits",
        "retrouvez nos derniers hors-séries, livres et unes du monde",
        "le monde avec afp",
        "affinez vos connaissances avec françoise barbe-gall, historienne de l’art.",
        "le monde mémorable",
        "temps de lecture 1 min.",
        "les meilleurs boucleurs à cheveux",
        "* imprimer l'article, * partager l'article sur facebook, * partager l'article sur twitter,",
        "contenu sponsorisé",
        "votre abonnement nous engage",
        "en vous abonnant, vous soutenez le projet de la rédaction de marianne : un journalisme libre, ni partisan, ni pactisant, toujours engagé ; un journalisme à la fois critique et force de proposition.",
        "natacha polony, directrice de la rédaction de marianne",
        "découvrez le numéro de la semaine",
        "lire le magazine",
        "les articles les plus lus",
        "le goût de la vérité n’empêche pas de prendre parti",
        "albert camus",
        "découvrir nos offres d’abonnement papier + numérique",
        "le magazine",
        "* déposer vos annonces légales, * voir nos annonces légales,",
        "* foire aux questions, * mentions légales, * données personnelles et cookies, * cgu et cgv, * formulaire de rétractation, * postuler à un stage, * flux rss,",
        "nos réseaux sociaux",
        "facebook twitter",
        "article abonné",
        "je m'abonne pour 1€",
        "default-output-block.skip-main",
        "offre spéciale - s'abonner",
        "* politique, * idées et débats, * monde, * climat et transitions, * economie, * tech et transformations, * entrepreneurs, * sciences et santé, * management, * education, * argent, * styles, * société, * culture,",
        "l’express – codes promos",
        "dellnikenocibé",
        "adidasmaisons du monde",
        "l’express franchiserénovation énergétique",
        "l’express xiiengagés auprès des français",
        "services de l’express",
        "newsletterslire le magazinel'express audio",
        "les podcasts de l’express",
        "partager cet article",
        "les plus lus",
        "consommer de la viande rouge, est-ce mauvais pour la santé ?",
        "la confir ...",
        '"pourquoi la france est-elle si riche ?"',
        ": la presse étrangère s’étonn ...",
        'jean-luc mélenchon, un "animal blessé" qui ourdit sa future candidatur ...',
        'bill browder, "l\'ennemi numéro un de poutine" : "je l’ai vu à l’œuvre, ...',
        "homéopathie, naturopathie, médecines douces : l’étonnant lobbying du c ...",
        '"oppenheimer" : son grand mérite, disculper albert einstein',
        "par etienne klein*",
        '"barbie" : ken, réveille-toi, ils sont devenus fous !',
        "par abnousse shalmani",
        "par christophe donner",
        "sur le même thème",
        "archives /2023202220212020201920182017201620152014201320122011",
        "* tous nos dossiers, * podcast la loupe, * 70 ans l'express, * séries d'été, * l'express canada, * articles sport, * articles beauté, * articles people, * articles vie perso, * articles vie intime,",
        "services partenaires",
        "* entreprendre en franchise, * l'express codes promo, * investir en scpi avec corum l'epargne, * comparateur de mutuelles avec devisprox,",
        "© l'express",
        "* mentions légales, * cookies, * politique de confidentialité, * conditions générales d'utilisation, * qui sommes-nous?, * service client, * boutique, * régie publicitaire,",
        "vous ne pouvez pas visionner ce contenu car :",
        "* vous avez refusé les cookies associés aux contenus issus de tiers en vous abonnant.",
        "vous ne pourrez donc pas lire nos vidéos qui ont besoin de cookies tiers pour fonctionner., * vous utilisez un bloqueur de publicité.",
        "nous vous conseillons de le désactiver afin d’accéder à nos vidéos.,",
        "si vous n'êtes dans aucun de ces deux cas, contactez-nous à aide@huffingtonpost.fr.",
        "envoyer une correction",
        "politique france international environnement life culture divertissement prise de parole vidéos jo paris 2024",
        "les sites du groupe",
        "courrier international",
        "le monde diplomatique",
        "suivez-nous",
        "facebook instagram twitter youtube dailymotion flipboard newsletters rss",
        "légal - infos",
        "gestion des cookies qui sommes-nous ?",
        "mentions légales conditions générales de vente politique de confidentialité publicité contactez nous faq plan du site",
        "par le huffpost",
        "le huffpost",
        "par le huffpost avec afp",
        "le huffpostafp",
        "photo d’illustration.",
        "julien de rosa / afp",
        "(photo d’illustration)",
        "franck fife / afp",
        "andreas malm adapté au cinéma : comment saboter un film",
        "emmanuel dunand / afp",
        "ludovic marin / afp",
        "voir la vidéo",
        "miguel medina / afp",
        "abonnez-vous 0,99€ le premier mois",
        "covid : se revacciner vite ou attendre ?",
        "l’avis des experts",
        "des prigojine en puissance ?",
        "en russie, les gouverneurs entrent en gue ...",
        '"on pensait que c’était fini" : comment le covid rattrape les français ...',
        '"elle va être ingérable" : sabrina agresti-roubache, le premier faux p ...',
        "* nos applications mobiles, * suivre le figaro sur google actu, * le figaro nantes, * le figaro lyon, * le figaro bordeaux, * le figaro nice, * les vidéos figaro live, * les podcasts du figaro, * les programmes tv, * les résultats sportifs, * carnet du jour, * figaro store,",
        "à voir également sur\xa0le huffpost\xa0:",
        "à voir également sur le\xa0huffpost\xa0:",
        "publié \n                il y a 2 heures,        \n                 mis à jour il y a 2 heures",
        "mis à jour le",
        "à voir aussi sur le huffpost\xa0:",
        "publié \n                il y a 1 heure,        \n                 mis à jour il y a 1 heure",
        "publié \n                il y a 3 heures,        \n                 mis à jour il y a 3 heures",
        "à voir aussi sur\xa0le huffpost\xa0:",
        "les infos à retenir",
        "voir le produit",
        "lorsque vous achetez via nos liens de vente, nous pouvons percevoir une commission d'affiliation.",
        "(e.\xa0garnier/l'équipe)",
        "les commentaires sont soumis à des règles de modération.",
        "lire la charte",
        "il n’y a pas encore de commentaire à cet article.",
        "(a. martin/l'équipe)",
        "(p.\xa0lahalle/l'équipe)",
        "(n.\xa0luttiau/l'équipe)",
        "(a. réau/l'équipe)",
        "(s.\xa0boué/l'équipe)",
        "(b.\xa0papon/l'équipe)",
        "(f.\xa0faugère/l'équipe)",
        "(a. mounic/l'équipe)",
        "(s.\xa0mantey/l'équipe)",
        "pas le temps de lire cet article ?",
        "découvrez la lecture audio.",
        "contenu conçu et proposé par le figaro services .",
    ]
    + [  # English Patterns
        "skip past newsletter promotion sign up to first edition free daily newsletter archie bland and nimo omer take you through the top stories and what they mean, free every weekday morning privacy notice: newsletters may contain info about charities, online ads, and content funded by outside parties.",
        "for more information see our newsletters may contain info about charities, online ads, and content funded by outside parties.",
        "for more information see our privacy policy .",
        "we use google recaptcha to protect our website and the google privacy policy and terms of service apply.",
        "after newsletter promotion",
        "sign up to newsletter",
        "make a donation",
        "skip past newsletter promotion sign up to business today free daily newsletter get set for the working day – we'll point you to all the business news and analysis you need every morning privacy notice: newsletters may contain info about charities, online ads, and content funded by outside parties.",
        "if you buy something using links in our stories, we may earn a commission.",
        "this helps support our journalism.",
        "learn more.",
        "image caption,",
        "privacy notice: newsletters may contain info about charities, online ads, and content funded by outside parties.",
        "previous slide",
        "image source, getty images",
        "we may earn a commission from links on this page.",
        "advertisement",
        "image source, reuters",
        "subscriptions",
        "image source, pa media",
        "get more from wired",
        "all rights reserved.",
        "skip to main content",
        "to revisit this article, select my account, then view saved stories",
        "to revisit this article, visit my profile, then view saved stories",
        "find anything you save across the site in your account",
        "new yorker favorites",
        "sign up for our daily newsletter to receive the best stories from the new yorker.",
        "© 2023 condé nast.",
        "use of this site constitutes acceptance of our user agreement and privacy policy and cookie statement and your california privacy rights.",
        "the new yorker may earn a portion of sales from products that are purchased through our site as part of our affiliate partnerships with retailers.",
        "the material on this site may not be reproduced, distributed, transmitted, cached or otherwise used, except with the prior written permission of condé nast.",
        "a reporter at large",
        "* the onion, * the a.v.",
        "club, * deadspin, * gizmodo, * jalopnik, * jezebel, * kotaku, * quartz, * the root, * the takeout, * the inventory,",
        "america's finest news source.",
        "send us a tip!shopsubscribe",
        "* off, * english,",
        "share this video",
        "facebooktwitteremail",
        "to revist this article, visit my profile, then view saved stories.",
        "* backchannel, * business, * culture, * gear, * ideas, * science, * security,",
        "* podcasts, * video, * artificial intelligence, * climate, * games, * newsletters, * magazine, * events, * wired insider, * jobs, * coupons,",
        "most popular",
        "this site is protected by recaptcha and the google privacy policy and terms of service apply.",
        "by signing up, you agree to our user agreement and privacy policy & cookie statement.",
        "our flagship newsletter highlights the best of the new yorker, including top stories, fiction, humor, and podcasts.",
        "e-mail address",
        "more from wired",
        "wired is where tomorrow is realized.",
        "it is the essential source of information and ideas that make sense of a world in constant transformation.",
        "the wired conversation illuminates how technology is changing every aspect of our lives—from culture to business, science to design.",
        "the breakthroughs and innovations that we uncover lead to new ways of thinking, new connections, and new industries.",
        "wired may earn a portion of sales from products that are purchased through our site as part of our affiliate partnerships with retailers.",
        "select international site",
        "* uk, * italia, * japón,",
        "please also consider subscribing to wired",
        "subscribe now",
        "view introductory offers",
        "no commitment, cancel anytime*",
        "offer ends 14th june 2023.",
        "*cancel anytime within 14 days of payment to receive a refund on unserved issues.",
        "inclusive of applicable taxes (vat)",
        "existing subscribers",
        "sign in to your account",
        "more from new scientist",
        "explore the latest news, articles and features",
        "subscriber-only",
        "popular articles",
        "trending new scientist articles",
        "download the app",
        "find us on social media",
        "* instagram, * facebook, * twitter, * tiktok, * linkedin,",
        "* subscriber benefits, * gift, * student, * educational, * corporate,",
        "* help, * about us, * advertise, * write for us,",
        "* events, * science jobs, * colab, * syndication, * rss feeds,",
        "legal and privacy",
        "* contact us, * privacy policy, * cookie policy, * terms & conditions,",
        "© copyright new scientist ltd.",
        "skip to main contentskip to navigationskip to navigation",
        "print subscriptions",
        "search jobs",
        "* international edition, * uk edition, * us edition, * australia edition,",
        "the guardian - back to homethe guardian",
        "* world, * europe, * us, * americas, * asia, * australia, * middle east, * africa, * inequality, * global development,",
        "skip past newsletter promotion",
        "free daily newsletter",
        "for more information see our privacy policy.",
        "reuse this content",
        "more on this story",
        "most viewed",
        "* news, * opinion, * sport, * culture, * lifestyle,",
        "original reporting and incisive analysis, direct from the guardian every morning",
        "sign up for our email",
        "* help, * complaints & corrections, * securedrop, * work for us, * privacy policy, * cookie policy, * terms & conditions, * contact us,",
        "* all topics, * all writers, * digital newspaper archive, * facebook, * youtube, * instagram, * linkedin, * twitter, * newsletters,",
        "* advertise with us, * search uk jobs,",
        "back to top",
        "© 2023 guardian news & media limited or its affiliated companies.",
        "* books, * music, * tv & radio, * art & design, * film, * games, * classical, * stage,",
        "* published1 hour ago,",
        "about sharing",
        "related topics",
        "top stories",
        "elsewhere on the bbc",
        "* home, * news, * sport, * reel, * worklife, * travel, * future, * culture, * music, * tv, * weather, * sounds,",
        "* terms of use, * about the bbc, * privacy policy, * cookies, * accessibility help, * parental guidance, * contact the bbc, * get personalised newsletters, * why you can trust the bbc, * advertise with us,",
        "â© 2023 bbc.",
        "the bbc is not responsible for the content of external sites.",
        "read about our approach to external linking.",
        "media caption,",
        "* published2 hours ago,",
        "* published5 hours ago,",
        "* published3 hours ago,",
        "explore more",
        "editor's recommendations",
        "accessibility links",
        "* skip to content, * accessibility help,",
        "bbc account",
        "notifications",
        "search bbc search bbc",
        "bbcsportall sport",
        "also in sport",
        "explore the bbc",
        "* terms of use, * about the bbc, * privacy policy, * privacy policy, * cookies, * cookies, * accessibility help, * parental guidance, * contact the bbc, * make an editorial complaint, * bbc emails for you, * advertise with us,",
        "copyright © 2023 bbc.",
        "explore hbr",
        "* tweet, * post, * share, * annotate, * save, * print,",
        "* uk, * uk politics, * education, * media, * society, * law, * scotland, * wales, * northern ireland,",
        "sign up to business today",
        "get set for the working day – we'll point you to all the business news and analysis you need every morning",
        "free weekly newsletter",
        "* business, * economics, * banking, * money, * markets, * project syndicate, * b2b, * retail,",
        "* world, * uk, * climate crisis, * environment, * science, * global development, * football, * tech, * business, * obituaries,",
        "* money, * property, * pensions, * savings, * borrowing, * careers,",
        "support the guardian",
        "related internet links",
        "* how to follow your premier league team on the bbceverything you need to know to make sure you never miss a moment., * today's football gossipthe latest rumours and stories from around the world of football., * phil mcnultyanalysis and opinion from our chief football writer., * how to get into footballhow to get into football - the most popular sport in the world, with clubs and facilities throughout the uk.,",
        "from other local news sites",
        "information about bbc links to other news sites",
        "join the conversation",
        "* the great resignation is over, say experts, * the protectors of a 7,000-year-old faith, * what colour should you wear in the heat?,",
        "now playing",
        "* the world's largest landlocked country, * which is the best sleeping position?, * the 'npc' trend sweeping tiktok,",
        "* the new napoleon film stirring debate, * stunning photos of a new african wonder, * why electric crops may soon be on the menu,",
        "- source:\n                cnn",
    ]
    + [  # Dutch Patterns
        "heeft u vragen, suggesties of ideeën over onze journalistiek?",
        "mail dan naar onze ombudsman via ombudsman@nrc.nl.",
        "goedemorgen!",
        "ga je de weg op?",
        "hier vind je het overzicht van de werkzaamheden.",
        "rtv utrecht",
        "omroep gelderland",
        "lezers zijn de auteurs van deze rubriek.",
        "insturen via ik@nrc.nl",
        "omroep brabant",
        "omroep zeeland",
        "lees ze hier terug.",
        "omroep flevoland",
        "kopieer de link van het artikel",
        "best gelezen",
        "instellingen",
        "* mijn account, * inloggenu bent niet ingelogd, * uitloggen,",
        "personaliseren",
        "* meldingen, * nieuwsbrieven, * mijn nieuwsbrieven, * data en privacydata en privacyprivacy-instellingencookiebeleidprivacy,",
        "* digitale krant, * winkel, * puzzels,",
        "vragen & contact",
        "* klantenservice, * tip de redactie, * familieberichten plaatsen, * wat vindt u van deze website?, * gebruiksvoorwaarden,",
        "* digitale editie, * puzzels,",
        "* cultuur&media, * duurzaamheid&economie, * opinie, * podcasts, * politiek, * puzzels, * recepten, * religie&filosofie, * sport, * tijdgeest, * verdieping, * wetenschap,",
        "wilt u iets delen met trouw?",
        "tip hier onze journalisten",
        "* over ons, * contact met trouw, * privacystatement, * abonnementsvoorwaarden, * gebruiksvoorwaarden, * cookiebeleid, * privacy-instellingen, * auteursrecht, * colofon,",
        "* klantenservice, * mijn omgeving, * vakantieservice, * adverteren, * losse verkoop,",
        "* abonneren, * nieuwsbrieven, * digitale krant, * webwinkel, * rss-feeds, * facebook, * twitter, * android apps, * ios apps,",
        "* columnisten, * recensies, * archief,",
        "op alle verhalen van trouw rust uiteraard copyright.",
        "wil je tekst overnemen of een video(fragment), foto of illustratie gebruiken, mail dan naar copyright@trouw.nl.",
        "© 2023 dpg media b.v. - alle rechten voorbehouden",
        "meer buitenland",
        "abonneren mijn nieuws podcasts digitale krant",
        "neem een abonnement",
        "mijn nieuws mijn leeslijst mijn geschiedenis digitale krant",
        "nieuwsbrieven onderwerpen",
        "ik ben abonnee neem een abonnement",
        "privacy-instellingen notificaties",
        "bezorgservice vakantieservice verhuisservice mijn gegevens mijn abonnementen abonnement delen gedeeld abonnement faq digitaal lezen veelgestelde vragen wachtwoord vergeten",
        "terug naar de krant",
        "al abonnee?",
        "het kan zijn dat elementen ontbreken aan deze printversie.",
        "luister meer...",
        "leestijd 2 minuten",
        "meld een taalfout",
        "toevoegen aan",
        "+ verzameling",
        "lees ook deze artikelen",
        "* over nrc, * over ons, * werken bij, * auteursrecht, * privacy, * leveringsvoorwaarden, * nrc-code, * onze app, * archief, * adverteren,",
        "* mijn nrc, * neem een abonnement, * inloggen, * account aanmaken, * digitale krant, * mijn leeslijst, * mijn abonnementen, * service & bezorging, * nieuwsbrieven,",
        "* contact, * redactie, * opinieredactie, * de ombudsman, * colofon, * adsales, * klantenservice, * familieberichten,",
        "* nrc websites, * mediahuis nrc, * nrc carrière, * nrc webwinkel, * nrc lezersfonds,",
        "leestijd 3 minuten",
        "leestijd 1 minuut",
        "* ga naar het menu, * ga naar de inhoud,",
        "deel artikel:",
        "advertentie via ster.nl",
        "tip de redactiegeef je tips aan ons door",
        "publieksvoorlichtingvoor vragen en reacties",
        "nos informatie",
        "* over de nos, * werken bij de nos, * contact, * journalistieke verantwoording, * herstelrubriek, * ombudsman npo, * nos apps, * voorwaarden, * privacy,",
        "* voorpagina, * laatste nieuws, * video's, * binnenland, * buitenland, * regionaal nieuws, * politiek, * economie, * koningshuis, * tech, * cultuur & media, * opmerkelijk, * archief,",
        "* voorpagina, * video's, * voetbal, * formule 1, * wielrennen, * schaatsen, * tennis, * archief,",
        "© nos 2023cookie-instellingen",
        "in samenwerking met",
        "* buitenland,",
        "* binnenland,",
        "omrop fryslân",
        "omroep west",
        "rtv drenthe",
        "en hier zie je waar wordt gewerkt aan het spoor.",
        "een ikje is  een persoonlijke ervaring  of anekdote in maximaal  120 woorden.",
        "redacteur online",
        "redacteur tech",
        "nando kasteleijn",
        "redacteur economie",
        "redacteur buitenland",
        "redacteur binnenland",
        "oorlog hamas-israël",
        "u kunt ons met dit formulier daarover informeren, dat stellen wij zeer op prijs.",
        "berichten over andere zaken dan taalfouten of feitelijke onjuistheden worden niet gelezen.",
        "taalfout of feitelijke onjuistheid (maximaal 120 woorden)",
        "maximaal 120 woorden a.u.b.",
        "e-mailadres",
        "vul een correct e-mail adres in",
        "© 2024 dpg media b.v. - alle rechten voorbehouden",
        "geselecteerd door de redactie",
        "twitter bericht wordt geladen...",
    ]
)

JUNK_PREFIXES = [
    "Der er ikke oplæsning af denne artikel, så den oplæses derfor med maskinstemme."
]

"""

    Sometimes newspaper/readability still leaves some individual fragments
    in the article.text.


:param text:
:return:
"""

print("-------->>>>> at the beginning of content_cleaner.py")


def normalize_sent(text: str):
    return text.lower().strip()


def filter_noise_patterns(article, sent_filter_set, crawl_report, feed, url):
    clean_artcile = ""
    for paragraph in article.split("\n\n"):
        clean_paragraph = ""
        is_prev_skip = False
        for sent in sent_tokenize(paragraph):
            if is_prev_skip and len(sent) <= 10:
                print("Skipped (Prev Skipped and Short!): ", sent)
                crawl_report.add_sent_removed(feed, sent, url)
                continue
            else:
                is_prev_skip = False
            if normalize_sent(sent) in sent_filter_set:
                print("Skipped (Repetitive): ", sent)
                crawl_report.add_sent_removed(feed, sent, url)
                is_prev_skip = True
                continue
            clean_paragraph += sent + " "
        if len(clean_paragraph) < 10:
            continue
        clean_artcile += clean_paragraph + "\n\n"
    return clean_artcile.strip()


def cleanup_non_content_bits_w_crawl_report(text: str, crawl_report, feed, url) -> str:
    new_text = text
    new_text = filter_noise_patterns(
        text, set(JUNK_COUNT_PATTERNS), crawl_report, feed, url
    )
    for junk_pattern in JUNK_PATTERNS_TO_REMOVE:
        cleaned = new_text.replace(junk_pattern, "")

        if cleaned != new_text:
            crawl_report.add_sent_removed(feed, junk_pattern, url)
            print(f"- cleaned: {junk_pattern}")
            new_text = cleaned

    clean_text = ""
    for junk_prefix in JUNK_PREFIXES:
        for each in new_text.split("\n"):
            if each.startswith(junk_prefix):
                print(">>>> dropping the Paragraph: " + each)
                crawl_report.add_sent_removed(feed, junk_pattern, url)
                continue
            clean_text += each + "\n"

    return clean_text


def cleanup_non_content_bits(text: str):
    new_text = text
    new_text = filter_noise_patterns(text, set(JUNK_COUNT_PATTERNS), {})

    for junk_pattern in JUNK_PATTERNS_TO_REMOVE:
        cleaned = new_text.replace(junk_pattern, "")

        if cleaned != new_text:
            print(f"- cleaned: {junk_pattern}")
            new_text = cleaned

    clean_text = ""
    for junk_prefix in JUNK_PREFIXES:
        for each in new_text.split("\n"):
            if each.startswith(junk_prefix):
                print(">>>> dropping the Paragraph: " + each)
                continue
            clean_text += each + "\n"

    return clean_text


def cleanup_all_articles_in_language(language_code):
    language_id = Language.find(language_code).id
    all_articles = Article.query.filter_by(language_id=language_id).all()
    for each in all_articles:
        cleaned_content = cleanup_non_content_bits(each.content)
        if cleaned_content != each.content:
            each.content = cleaned_content
            zeeguu.core.model.db.session.add(each)
            print(each.title + "\n\n")
    zeeguu.core.model.db.session.commit()
