"""
English multi-word expressions.
"""

ENGLISH_MWES = frozenset({
    # Prepositional idioms
    "in spite of",
    "in lieu of",
    "in light of",
    "in view of",
    "in terms of",
    "in addition to",
    "in accordance with",
    "in front of",
    "in favor of",
    "in favour of",
    "in case of",
    "in the event of",
    "on behalf of",
    "on the basis of",
    "on top of",
    "on the verge of",
    "on the hunt for",
    "on the lookout for",
    "by means of",
    "by virtue of",
    "by way of",
    "with regard to",
    "with respect to",
    "with reference to",
    "as a result of",
    "as opposed to",
    "as well as",
    "ahead of",
    "instead of",
    "regardless of",
    "according to",
    "thanks to",
    "due to",
    "owing to",
    "prior to",
    "subject to",

    # Light-verb constructions
    "take into account",
    "take into consideration",
    "take advantage of",
    "take care of",
    "make use of",
    "make sense of",
    "give rise to",
    "pay attention to",
    "keep an eye on",
    "keep track of",
    "get rid of",
    "come up with",
    "look forward to",
})
