from zeeguu.api.test.fixtures import test_app


def test_routes_do_not_end_with_slash(test_app):

    # There are only two routes in the application which are
    # allowed to end in slash:
    # 1. the root page
    # 2. the page generated by the FMD
    exceptions = ["/", "/dashboard/"]

    # We test all the other route names
    route_names = [
        rule.rule
        for rule in test_app.url_map.iter_rules()
        if rule.rule not in exceptions
    ]
    print(route_names)

    for name in route_names:
        if name.endswith("/"):
            assert False, f"{name}: Endpoint names should not end in /"
